Login: "dtrishkin@mirantis.com"
Password: ""
Branch:  openstack-ci/fuel-7.0/2015.1.0 #"openstack-ci/fuel-7.0/2015.1.0" #"openstack-ci/fuel-7.0/2014.2" #"openstack-ci/fuel-6.1/2014.2" #6.1 #7.0
RepoNames: True # Repo name before list of it dependencies
IgnoreUnknown: True # Ignore unknown packages with "python-" prefix
Templates: [['https://review.fuel-infra.org/gitweb?p=openstack-build/{0}.git;a=blob_plain;f=debian/{2};hb=refs/heads/{1}', "control", "url1"],
['https://review.fuel-infra.org/gitweb?p=packages/trusty/{0}.git;a=blob_plain;f=debian/{2};hb=refs/heads/{1}', "control", "url2"],
['https://review.fuel-infra.org/gitweb?p=packages/precise/{0}.git;a=blob_plain;f=debian/{2};hb=refs/heads/{1}', "control", "url3"],
['https://review.fuel-infra.org/gitweb?p=openstack-build/{0}.git;a=blob_plain;f=trusty/debian/{2};hb=refs/heads/{1}', "control", "url4"]]
# ({0}repo, {1}branch, {2}file) file have to be specified after link template ["control", "spec"]
# ['url template', "control|spec", "name of output file"]
